name: 'actions-setup-redis'
description: 'setup redis database'
author: 'Ichinose Shogo'
inputs:
  redis-version:
    description: the version of redis
    default: "5"
  redis-port:
    description: the port of redis-sever
    default: "6379"
  auto-restart:
    description: enable to auto-start redis-sever
    default: "yes"
runs:
  using: 'node12'
  main: 'lib/setup-redis.js'
