name: 'actions-setup-redis'
description: 'setup redis database'
author: 'Ichinose Shogo'
inputs:
  redis-version:
    description: the version of redis
    default: 5
runs:
  using: 'node12'
  main: 'lib/setup-redis.js'
