name: 'actions-setup-redis'
description: 'setup redis database'
author: 'Ichinose Shogo'
inputs:
  redis-version:
    description: the version of redis
    default: "latest"
    required: true
  redis-port:
    description: the port of redis-sever
    default: "6379"
    required: true
  auto-start:
    description: enable to auto-start redis-sever
    default: "true"
    required: true
runs:
  using: 'node12'
  main: 'lib/setup-redis.js'
  post: 'lib/cleanup-redis.js'
  post-if: 'always()'
branding:
  icon: 'database'  
  color: 'red'
