name: build-3.2

on:
  push:
    branches:
      - "releases/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.15
        redis:
          - "3.2.13"
          - "3.2.12"
          - "3.2.11"
          - "3.2.10"
          - "3.2.9"
          - "3.2.8"
          - "3.2.7"
          - "3.2.6"
          - "3.2.5"
          - "3.2.4"
          - "3.2.3"
          - "3.2.2"
          - "3.2.1"
          - "3.2.0"
    steps:
      - uses: actions/checkout@v2
      - name: build
        shell: bash
        run: ./build-redis.sh "$REDIS_VERSION"
        env:
          REDIS_VERSION: ${{ matrix.redis }}
      - name: upload
        shell: bash
        run: |
          ACTIONS_VERSION=v$(cat "$GITHUB_WORKSPACE/package.json" | jq -r .version)
          OS=$(uname | tr '[A-Z]' '[a-z]')
          curl -sSL https://github.com/shogo82148/s3cli-mini/releases/download/v0.0.6/s3cli-mini_${OS}_amd64.tar.xz -o s3cli-mini.tar.xz
          tar xzvf s3cli-mini.tar.xz
          s3cli-mini_${OS}_amd64/s3cli-mini --region us-east-1 cp --acl public-read "$RUNNER_TEMP/redis-bin.tar.xz" "s3://shogo82148-actions-setup-redis/$ACTIONS_VERSION/redis-$REDIS_VERSION-${OS}-x64.tar.xz"
        env:
          REDIS_VERSION: ${{ matrix.redis }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
