name: build-2.8

on:
  push:
    branches:
      - 'releases/*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
        redis:
          - '2.8.24'
          - '2.8.23'
          - '2.8.22'
          - '2.8.21'
          - '2.8.20'
          - '2.8.19'
          - '2.8.18'
          - '2.8.17'
          - '2.8.16'
          - '2.8.15'
          - '2.8.14'
          - '2.8.13'
          - '2.8.12'
          - '2.8.11'
          - '2.8.10'
          - '2.8.9'
          - '2.8.8'
          - '2.8.7'
          - '2.8.6'
          - '2.8.5'
          - '2.8.4'
          - '2.8.3'
          - '2.8.2'
          - '2.8.1'
          - '2.8.0'
    steps:
      - uses: actions/checkout@v2
      - name: build
        shell: bash
        run: ./build-redis.sh "$REDIS_VERSION"
        env:
          REDIS_VERSION: ${{ matrix.redis }}
      - name: upload
        shell: bash
        run: |
          ACTIONS_VERSION=v$(cat "$GITHUB_WORKSPACE/package.json" | jq -r .version)
          OS=$(uname | tr '[A-Z]' '[a-z]')
          curl -sSL https://github.com/shogo82148/s3cli-mini/releases/download/v0.0.5/s3cli-mini_${OS}_amd64.tar.gz -o s3cli-mini.tar.gz
          tar xzvf s3cli-mini.tar.gz
          s3cli-mini_${OS}_amd64/s3cli-mini --region us-east-1 cp --acl public-read "$RUNNER_TEMP/redis-bin.tar.gz" "s3://shogo82148-actions-setup-redis/$ACTIONS_VERSION/redis-$REDIS_VERSION-${OS}-x64.tar.gz"
        env:
          REDIS_VERSION: ${{ matrix.redis }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
