name: build

on:
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - macOS-10.14
        redis:
        - '5.0.6'
        - '5.0.5'
        - '5.0.4'
        - '5.0.3'
        - '5.0.2'
        - '5.0.1'
        - '5.0.0'
        - '4.0.14'
        - '4.0.13'
        - '4.0.12'
        - '4.0.11'
        - '4.0.10'
        - '4.0.9'
        - '4.0.8'
        - '4.0.7'
        - '4.0.6'
        - '4.0.5'
        - '4.0.4'
        - '4.0.3'
        - '4.0.2'
        - '4.0.1'
        - '4.0.0'
        - '3.2.13'
        - '3.2.12'
        - '3.2.11'
        - '3.2.10'
        - '3.2.9'
        - '3.2.8'
        - '3.2.7'
        - '3.2.6'
        - '3.2.5'
        - '3.2.4'
        - '3.2.3'
        - '3.2.2'
        - '3.2.1'
        - '3.2.0'
        - '3.0.7'
        - '3.0.6'
        - '3.0.5'
        - '3.0.4'
        - '3.0.3'
        - '3.0.2'
        - '3.0.1'
        - '3.0.0'
        - '2.8.24'
        - '2.8.23'
        - '2.8.22'
        - '2.8.21'
        - '2.8.20'
        - '2.8.19'
        - '2.8.18'
        - '2.8.17'
        - '2.8.16'
        - '2.8.15'
        - '2.8.14'
        - '2.8.13'
        - '2.8.12'
        - '2.8.11'
        - '2.8.10'
        - '2.8.9'
        - '2.8.8'
        - '2.8.7'
        - '2.8.6'
        - '2.8.5'
        - '2.8.4'
        - '2.8.3'
        - '2.8.2'
        - '2.8.1'
        - '2.8.0'
        - '2.6.16'
        - '2.6.15'
        - '2.6.14'
        - '2.6.13'
        - '2.6.12'
        - '2.6.11'
        - '2.6.10'
        - '2.6.9'
        - '2.6.8'
        - '2.6.7'
        - '2.6.6'
        - '2.6.5'
        - '2.6.4'
        - '2.6.3'
        - '2.6.2'
        - '2.6.1'
        - '2.6.0'
        - '2.4.18'
        - '2.4.17'
        - '2.4.16'
        - '2.4.15'
        - '2.4.14'
        - '2.4.13'
        - '2.4.12'
        - '2.4.11'
        - '2.4.10'
        - '2.4.9'
        - '2.4.8'
        - '2.4.7'
        - '2.4.6'
        - '2.4.5'
        - '2.4.4'
        - '2.4.3'
        - '2.4.2'
        - '2.4.1'
        - '2.4.0'
        - '2.2.13'
        - '2.2.12'
        - '2.2.11'
        - '2.2.10'
        - '2.2.9'
        - '2.2.8'
        - '2.2.7'
        - '2.2.6'
        - '2.2.5'
        - '2.2.4'
        - '2.2.3'
        - '2.2.2'
        - '2.2.1'
        - '2.2.0'
        - '2.0.4'
        - '2.0.3'
        - '2.0.2'
        - '2.0.1'
        - '2.0.0'
    steps:
    - uses: actions/checkout@v1
    - name: build
      shell: bash
      run: ./build-redis.sh "$REDIS_VERSION"
      env:
        REDIS_VERSION: ${{ matrix.redis }}
    - name: upload
      shell: bash
      run: |
        ACTIONS_VERSION=v$(cat "$GITHUB_WORKSPACE/package.json" | jq -r .version)
        OS=$(uname | tr '[A-Z]' '[a-z]')
        curl -sSL https://github.com/shogo82148/s3cli-mini/releases/download/v0.0.2/s3cli-mini_${OS}_amd64.tar.gz -o s3cli-mini.tar.gz
        tar xzvf s3cli-mini.tar.gz
        s3cli-mini_${OS}_amd64/s3cli-mini --region us-east-1 cp --acl public-read "$RUNNER_TEMP/redis-bin.tar.gz" "s3://shogo82148-actions-setup-redis/$ACTIONS_VERSION/redis-$REDIS_VERSION-${OS}-x64.tar.gz"
      env:
        REDIS_VERSION: ${{ matrix.redis }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
