name: build-2.6

on:
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - macOS-10.14
        redis:
        - '2.6.16'
        - '2.6.15'
        - '2.6.14'
        - '2.6.13'
        - '2.6.12'
        - '2.6.11'
        - '2.6.10'
        - '2.6.9'
        - '2.6.8'
        - '2.6.7'
        - '2.6.6'
        - '2.6.5'
        - '2.6.4'
        - '2.6.3'
        - '2.6.2'
        - '2.6.1'
        - '2.6.0'
    steps:
    - uses: actions/checkout@v1
    - name: build
      shell: bash
      run: ./build-redis.sh "$REDIS_VERSION"
      env:
        REDIS_VERSION: ${{ matrix.redis }}
    - name: upload
      shell: bash
      run: |
        ACTIONS_VERSION=v$(cat "$GITHUB_WORKSPACE/package.json" | jq -r .version)
        OS=$(uname | tr '[A-Z]' '[a-z]')
        curl -sSL https://github.com/shogo82148/s3cli-mini/releases/download/v0.0.2/s3cli-mini_${OS}_amd64.tar.gz -o s3cli-mini.tar.gz
        tar xzvf s3cli-mini.tar.gz
        s3cli-mini_${OS}_amd64/s3cli-mini --region us-east-1 cp --acl public-read "$RUNNER_TEMP/redis-bin.tar.gz" "s3://shogo82148-actions-setup-redis/$ACTIONS_VERSION/redis-$REDIS_VERSION-${OS}-x64.tar.gz"
      env:
        REDIS_VERSION: ${{ matrix.redis }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
