name: build

on:
  push:
    branches:
    - '*'

jobs:
  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        # - windows-2019
        - macOS-10.14
        redis:
        - "5.0.5"
    steps:
    - uses: actions/checkout@v1
    - name: build
      shell: bash
      run: ./build-redis.sh "$REDIS_VERSION"
      env:
        REDIS_VERSION: ${{ matrix.redis }}
