name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-16.04
        - macOS-10.14

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        version: 12.x

    - name: npm install
      run: npm install

    - name: Lint
      run: npm run format-check
